name: export discussions

on:
  discussion:
    types: [created, edited, deleted]
  workflow_dispatch:

jobs:
  discussion-to-md:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.25"

      - uses: actions/checkout@v3

      - run: deno run --allow-net --allow-env --allow-read --allow-write scripts/fetchPosts.js

      - run: scripts/commit.bash
